### ISSUE TITLE
[BUG] - [vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by eyucherin** [heroui-inc/heroui#2078]
### NextUI Version

2.1.10

### Describe the bug

[vite] Internal server error: [postcss] Cannot read properties of undefined (reading 'toLowerCase')
  Plugin: vite:css
  File: /Users/eyucherin/Desktop/frontend/service/src/index.css
      at userAgentContains (/Users/eyucherin/Desktop/frontend/service/node_modules/framer-motion/dist/cjs/index.js:4223:25)
      at /Users/eyucherin/Desktop/frontend/service/node_modules/framer-motion/dist/cjs/index.js:4229:20
      at evalModule (/Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/node_modules/jiti/dist/jiti.js:1:255614)
      at jiti (/Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/node_modules/jiti/dist/jiti.js:1:253542)
      at /Users/eyucherin/Desktop/frontend/service/node_modules/@nextui-org/react/node_modules/@nextui-org/accordion/dist/index.js:44:29
      at evalModule (/Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/node_modules/jiti/dist/jiti.js:1:255614)
      at jiti (/Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/node_modules/jiti/dist/jiti.js:1:253542)
      at /Users/eyucherin/Desktop/frontend/service/node_modules/@nextui-org/react/dist/index.js:29:25
      at evalModule (/Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/node_modules/jiti/dist/jiti.js:1:255614)
      at jiti (/Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/node_modules/jiti/dist/jiti.js:1:253542)
      at /Users/eyucherin/Desktop/frontend/service/tailwind.config.cjs:1:89
      at evalModule (/Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/node_modules/jiti/dist/jiti.js:1:255614)
      at jiti (/Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/node_modules/jiti/dist/jiti.js:1:253542)
      at /Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/lib/lib/load-config.js:37:30
      at loadConfig (/Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/lib/lib/load-config.js:39:6)
      at getTailwindConfig (/Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:71:116)
      at /Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:100:92
      at /Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/lib/processTailwindFeatures.js:48:11
      at plugins (/Users/eyucherin/Desktop/frontend/service/node_modules/tailwindcss/lib/plugin.js:38:69)
      at LazyResult.runOnRoot (/Users/eyucherin/Desktop/frontend/service/node_modules/vite/node_modules/postcss/lib/lazy-result.js:357:16)
      at LazyResult.runAsync (/Users/eyucherin/Desktop/frontend/service/node_modules/vite/node_modules/postcss/lib/lazy-result.js:286:26)
      at LazyResult.async (/Users/eyucherin/Desktop/frontend/service/node_modules/vite/node_modules/postcss/lib/lazy-result.js:160:30)
      at LazyResult.then (/Users/eyucherin/Desktop/frontend/service/node_modules/vite/node_modules/postcss/lib/lazy-result.js:436:17)

### Steps to Reproduce the Bug or Issue

The error described above shows when I run my server I am using Vite on Mac and I am trying to incorporate NextUI into my project. 

when I comment out the nextui plugin in my tailwind config file, the error disappears but am not able to use nextui. This is inside a monorepo would this be a problem? It seems like some people in my team are not able to reproduce the issue. 

postcss looks like the following
```js
module.exports = {
    plugins: {
        tailwindcss: {},
        autoprefixer: {},
    },
};
```
tailwind looks like the following
```js
import { nextui } from '@nextui-org/react';

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './src/**/*.{js,ts,jsx,tsx}',
        '../component/src/**/*.{js,ts,jsx,tsx}',
        './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
        extend: {},
    },
    darkMode: 'class',
    plugins: [
        nextui({
            addCommonColors: true,
        }),
    ],
};
```

### Expected behavior

The error mentioned above

### Operating System Version

macOS

### Browser

Chrome

**Comment by 7haz** [comment]
Same issue here, 

1. created a new Vite project 
2. followed tailwinds installation guide 
3. followed nextUI installation guide

**Comment by anfreire** [comment]
same here :(

**Comment by jmy2022** [comment]
me too

**Comment by rwjCxgsy** [comment]
me too too

**Comment by Mingyang-Li** [comment]
@eyucherin  Simialr issue here, except I don't get errors when trying to render NextUI components. Instead, the NextUI components I tried to render simply look like plain HTML elements:
![image](https://github.com/nextui-org/nextui/assets/53138432/38d9b2d1-4163-410b-92ac-66d4e7f89939)

## Background
**Buggy behaviour**: The NextUI components I tried to render simply look like plain HTML elements 
**Repository type**: Monorepo (Turborepo)
**Package manager**: PNPM
**Location of the app I'm trying to NextUI into**: `/packages/portal`
**Type of application**: Next.js + Typescript + page-based routing + tRPC
**Version of `tailwindcss` installed**: 3.3.6
**Version of `postcss` installed**: 8.4.32
**Version of `autoprefixer` installed**: 10.4.16
**Version of `framer-motion` installed**: 10.16.16
**Version of `@nextui-org/react` installed**: 2.2.9

My `tailwind.config.css`
```js
import { nextui } from '@nextui-org/react';

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  darkMode: 'class',
  plugins: [nextui()],
};

export default config;
```

My `postcss.config.js`:
```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
```

According to the [doc](https://nextui.org/docs/frameworks/nextjs), i also had to setup pnpm `.npmrc`, so I did, like this:

My `.npmrc` in `/packages/portal/` folder (where I want to use NextUI):
```
public-hoist-pattern[]=*@nextui-org/*
```

My `.npmrc` at root folder:
```
auto-install-peers = true
save-exact=true
```
## ⚠️ Other miscellaneous findings:
After I installed `@nextui-org/react` into `packages/portal` Next.js app, the `packages/node_modules` only has `@nextui-org/react` package, but all the actual components are in the `node_modules` of the root folder...

My questions:
- Why do you think is this happening?
- Is it intentional by design?
- Could this be the reason I cannot render NextUI components properly?
- How to I render them properly?

Node modules of the Next.js app
![image](https://github.com/nextui-org/nextui/assets/53138432/6ae04dcf-5442-4ba0-b581-7e391d1a3f70)

Node modules of the monorepo root folder
![image](https://github.com/nextui-org/nextui/assets/53138432/461b1ade-3ef6-4f40-9285-8a084cc8d019)

**Comment by Mingyang-Li** [comment]
Update - I manually moved the `@nextui-org` folder from root folder node_modules into `packages/portal/node_modules`, the components are now starting to work - aka rendering the same way as on the doc.

I just need to find out why `@nextui-org` gets installed in the root directory. I suspect it's got something to do with `public-hoist-pattern[]=*@nextui-org/*` in the `.npmrc` file

**Comment by anfreire** [comment]
All I had to do was switch to a more recent Tailwind configuration.


# OLD

```
import { nextui } from '@nextui-org/react';

/** @type {import('tailwindcss').Config} */
const config = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  darkMode: 'class',
  plugins: [nextui()],
};

export default config;
```

---

# NEW

```
const { nextui } = require("@nextui-org/react");

/** @type {import('tailwindcss').Config} */
module.exports = {
      content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {},
  },
  darkMode: "class",
  plugins: [nextui()],
};
```

**Comment by PaVeilleux** [comment]
> @eyucherin Similar issue here, except I don't get errors when trying to render NextUI components. Instead, the NextUI components I tried to render simply look like plain HTML elements: ![image](https://private-user-images.githubusercontent.com/53138432/293111425-38d9b2d1-4163-410b-92ac-66d4e7f89939.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMzQ5ODAsIm5iZiI6MTcxNjMzNDY4MCwicGF0aCI6Ii81MzEzODQzMi8yOTMxMTE0MjUtMzhkOWIyZDEtNDE2My00MTBiLTkyYWMtNjZkNGU3Zjg5OTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDIzMzgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NzYzNDJlNWU2YzNkMGRmZjU2MTQ3OThhMTRmMTgyMGE1MTViNjlkNGRkY2I4ZDQxZThjNmU4ZDE3YjhjYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E4iTeCIXFXgkxAVQKFZsnS_WgNbSm-wGUokDYNpc7iM)
> 
> ## Background
> **Buggy behaviour**: The NextUI components I tried to render simply look like plain HTML elements **Repository type**: Monorepo (Turborepo) **Package manager**: PNPM **Location of the app I'm trying to NextUI into**: `/packages/portal` **Type of application**: Next.js + Typescript + page-based routing + tRPC **Version of `tailwindcss` installed**: 3.3.6 **Version of `postcss` installed**: 8.4.32 **Version of `autoprefixer` installed**: 10.4.16 **Version of `framer-motion` installed**: 10.16.16 **Version of `@nextui-org/react` installed**: 2.2.9
> 
> My `tailwind.config.css`
> 
> ```js
> import { nextui } from '@nextui-org/react';
> 
> /** @type {import('tailwindcss').Config} */
> const config = {
>   content: [
>     "./src/**/*.{js,ts,jsx,tsx,mdx}",
>     './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
>   ],
>   theme: {
>     extend: {},
>   },
>   darkMode: 'class',
>   plugins: [nextui()],
> };
> 
> export default config;
> ```
> 
> My `postcss.config.js`:
> 
> ```js
> module.exports = {
>   plugins: {
>     tailwindcss: {},
>     autoprefixer: {},
>   },
> }
> ```
> 
> According to the [doc](https://nextui.org/docs/frameworks/nextjs), i also had to setup pnpm `.npmrc`, so I did, like this:
> 
> My `.npmrc` in `/packages/portal/` folder (where I want to use NextUI):
> 
> ```
> public-hoist-pattern[]=*@nextui-org/*
> ```
> 
> My `.npmrc` at root folder:
> 
> ```
> auto-install-peers = true
> save-exact=true
> ```
> 
> My `global.css` which sits in `packages/portal/src/styles/`
> 
> ```css
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```
> 
> My `_app.tsx` from `packages/portal/src/pages/`
> 
> ```tsx
> import { type AppType } from 'next/app';
> import { NextUIProvider } from '@nextui-org/react';
> import { api } from '@/utils/api';
> import '@/styles/global.css';
> 
> const App: AppType = ({ Component, pageProps }) => {
>   return (
>     <NextUIProvider>
>       <Component {...pageProps} />
>     </NextUIProvider>
>   );
> };
> 
> export default api.withTRPC(App);
> ```
> 
> Note: I'm using aosolute import path alias, which means `import '@/styles/global.css';` could've been `import '../styles/global.css';`
> 
> ## ⚠️ Other miscellaneous findings:
> After I installed `@nextui-org/react` into `packages/portal` Next.js app, the `packages/node_modules` only has `@nextui-org/react` package, but all the actual components are in the `node_modules` of the root folder...
> 
> My questions:
> 
> * Why do you think is this happening?
> * ~Is it intentional by design?~ - No
> * ~Could this be the reason I cannot render NextUI components properly?~ - Yes
> * ~How do I render them properly?~ - Make sure the `@nextui-org` folder is in the node_modules of the app that you want to integrate NextUI into
> 
> Node modules of the Next.js app ![image](https://private-user-images.githubusercontent.com/53138432/293112113-6ae04dcf-5442-4ba0-b581-7e391d1a3f70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMzQ5ODAsIm5iZiI6MTcxNjMzNDY4MCwicGF0aCI6Ii81MzEzODQzMi8yOTMxMTIxMTMtNmFlMDRkY2YtNTQ0Mi00YmEwLWI1ODEtN2UzOTFkMWEzZjcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDIzMzgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NDdhOGY4MzI2YTU2ZmNiOWIyOGM3NzZkZDIzN2JkM2EwMmQ4MDMzMWRhZmQ0N2U0MGQ0ZGMwMjc4OTRhZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJwx2306LoLlgZixDj3SCu1dbPirRQf3jcUgcX-zewM)
> 
> Node modules of the monorepo root folder ![image](https://private-user-images.githubusercontent.com/53138432/293112162-461b1ade-3ef6-4f40-9285-8a084cc8d019.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMzQ5ODAsIm5iZiI6MTcxNjMzNDY4MCwicGF0aCI6Ii81MzEzODQzMi8yOTMxMTIxNjItNDYxYjFhZGUtM2VmNi00ZjQwLTkyODUtOGEwODRjYzhkMDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDIzMzgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YTNjNGI1NDVkNzllZDkxOTYyYjU1MWFkMTNkY2Y1YjY0NTYwNDg4MTM0ZjYxMjhiNzVlNzQwOGUyZDI1YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2GgCYQTOk0MgIMa3JUKRyhLd7ZO7CKP1wDjDbnXByGg)

Do you have any updates on the node_modules behavior ? i have the same problem i can't make it work...

**Comment by PaVeilleux** [comment]
> Update - I manually moved the `@nextui-org` folder from root folder node_modules into `packages/portal/node_modules`, the components are now starting to work - aka rendering the same way as on the doc.
> 
> I just need to find out why `@nextui-org` gets installed in the root directory. I suspect it's got something to do with `public-hoist-pattern[]=*@nextui-org/*` in the `.npmrc` file

Do you have any updates on this ? I have the same issue...

**Comment by wingkwong** [comment]
You only add the following line when you are using pnpm. 

```
public-hoist-pattern[]=*@nextui-org/*
```

You may refer to our vite template: https://github.com/nextui-org/vite-template
